
version: '3.1'

services:

  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "6033:3306"
    volumes:
      - ./docker-volumes-data/db:/var/lib/database
    environment:
      MYSQL_DATABASE: bus_booking
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_USER: User


  phpmyadmin:
    container_name: pma
    image: phpmyadmin
    restart: always
    links:
      - db
    ports:
      - 8082:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
